### PR TITLE
added email on error and success

### PR DESCRIPTION
**Pull request by ryssbowh**
Hi,

This is a merge request to add some email sending when a schedule succeeds or fails.
Each schedule can have those settings, and the email will contain the output of the schedule, if the logs were enabled for it.

I believe this would be very useful for users who needs to know if a schedule has failed so they can fix it

### CODE REVIEW

**Comment by panlatent** [comment]
Thanks for your PR.

Since I haven't worked in a CraftCMS environment recently, I just browsed your code and it didn't work, sorry if there are any mistakes.

I think adding Email support is good, but Email is not the only notification channel for this feature. Although we don't have the energy to do much at the moment, there should be a good design to facilitate future expansion.

There may also be several potential problems:

A large number of runs in a short period of time may result in many spam emails
Lack of unified settings and controls, users may prefer unified configuration for all tasks (EMail)

**Comment by ryssbowh** [comment]
You're right, best to do things properly :

Notifications are abstracted now, they can be registered through events. The system comes with two types : Email and Slack.
Notifications can be added to each schedule, just like timers, they have their own settings.

Slack api token is a global setting as well as a setting that can be overridden in each notification.
Email notification can have several email addresses.
Both notifications have been tested with defualt mailer and my own slack team.

There's a global setting to disable all notifications.

I haven't made a global notification system, I don't see it working to be honest, with this new features, notifications can be added to each schedule easily.
Large number of runs problems, to me this is up to the user at this point to not use emails for such schedules ? we can implement some threshold but that's not gonna be an easy feature.

**Comment by panlatent** [comment]
Hi. I'm sorry it took so long.

This is a useful feature. I tried to merge your code, but chose not to. I think we can make it better.

There are a few minor formatting issues with the code you submitted that I have noticed: inconsistent type constraints and comments, and poor typing.

I've been thinking a lot about how to design this feature.

It's smart to design multiple channels instead of just using EMail, but do we need a separate notification type? Sending notifications isn't really any different from executing various Scheduel duel routines, it's just that they're triggered differently.

Perhaps we could design an Action class that contains multiple actions and is then used by Schedules or Notifications.

Of course, changing the design would require extra work, so I was wondering if I could fix minor bugs in the current code and work on these ideas for the next version.

Due to my misoperation, this PR was closed. Please submit a new PR again.

**Comment by ryssbowh** [comment]
Hi,

Not sure what you're asking, do you want another PR just the same ?
I can't see the typing problems in a quick look, can you expand.
Also I don't understand what you said : "we could design an Action class that contains multiple actions and is then used by Schedules or Notifications."

**Pull request merged**
